<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BuildEquipmentSeeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('builds_equipments')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('builds_equipments')->insert(array (
            ['id' => 1, 'build_id' => 1, 'equipment_id' => 4, 'tipo' => 1],
            ['id' => 2, 'build_id' => 1, 'equipment_id' => 11, 'tipo' => 2],
            ['id' => 3, 'build_id' => 1, 'equipment_id' => 17, 'tipo' => 2],
            ['id' => 4, 'build_id' => 1, 'equipment_id' => 18, 'tipo' => 2],
            ['id' => 5, 'build_id' => 1, 'equipment_id' => 19, 'tipo' => 2],
            ['id' => 6, 'build_id' => 1, 'equipment_id' => 20, 'tipo' => 2],
            ['id' => 7, 'build_id' => 1, 'equipment_id' => 4, 'tipo' => 3],
            ['id' => 8, 'build_id' => 2, 'equipment_id' => 3, 'tipo' => 1],
            ['id' => 9, 'build_id' => 2, 'equipment_id' => 11, 'tipo' => 2],
            ['id' => 10, 'build_id' => 2, 'equipment_id' => 12, 'tipo' => 2],
            ['id' => 11, 'build_id' => 2, 'equipment_id' => 13, 'tipo' => 2],
            ['id' => 12, 'build_id' => 2, 'equipment_id' => 14, 'tipo' => 2],
            ['id' => 13, 'build_id' => 2, 'equipment_id' => 20, 'tipo' => 2],
            ['id' => 14, 'build_id' => 2, 'equipment_id' => 2, 'tipo' => 3],
            ['id' => 15, 'build_id' => 3, 'equipment_id' => 3, 'tipo' => 1],
            ['id' => 16, 'build_id' => 3, 'equipment_id' => 11, 'tipo' => 2],
            ['id' => 17, 'build_id' => 3, 'equipment_id' => 12, 'tipo' => 2],
            ['id' => 18, 'build_id' => 3, 'equipment_id' => 13, 'tipo' => 2],
            ['id' => 19, 'build_id' => 3, 'equipment_id' => 19, 'tipo' => 2],
            ['id' => 20, 'build_id' => 3, 'equipment_id' => 20, 'tipo' => 2],
            ['id' => 21, 'build_id' => 3, 'equipment_id' => 4, 'tipo' => 3],
            ['id' => 22, 'build_id' => 4, 'equipment_id' => 4, 'tipo' => 1],
            ['id' => 23, 'build_id' => 4, 'equipment_id' => 11, 'tipo' => 2],
            ['id' => 24, 'build_id' => 4, 'equipment_id' => 17, 'tipo' => 2],
            ['id' => 25, 'build_id' => 4, 'equipment_id' => 18, 'tipo' => 2],
            ['id' => 26, 'build_id' => 4, 'equipment_id' => 19, 'tipo' => 2],
            ['id' => 27, 'build_id' => 4, 'equipment_id' => 20, 'tipo' => 2],
            ['id' => 28, 'build_id' => 4, 'equipment_id' => 5, 'tipo' => 3],
            ['id' => 29, 'build_id' => 5, 'equipment_id' => 4, 'tipo' => 1],
            ['id' => 30, 'build_id' => 5, 'equipment_id' => 21, 'tipo' => 2],
            ['id' => 31, 'build_id' => 5, 'equipment_id' => 22, 'tipo' => 2],
            ['id' => 32, 'build_id' => 5, 'equipment_id' => 18, 'tipo' => 2],
            ['id' => 33, 'build_id' => 5, 'equipment_id' => 19, 'tipo' => 2],
            ['id' => 34, 'build_id' => 5, 'equipment_id' => 20, 'tipo' => 2],
            ['id' => 35, 'build_id' => 5, 'equipment_id' => 4, 'tipo' => 3],
            ['id' => 36, 'build_id' => 6, 'equipment_id' => 4, 'tipo' => 1],
            ['id' => 37, 'build_id' => 6, 'equipment_id' => 11, 'tipo' => 2],
            ['id' => 38, 'build_id' => 6, 'equipment_id' => 27, 'tipo' => 2],
            ['id' => 39, 'build_id' => 6, 'equipment_id' => 23, 'tipo' => 2],
            ['id' => 40, 'build_id' => 6, 'equipment_id' => 34, 'tipo' => 2],
            ['id' => 41, 'build_id' => 6, 'equipment_id' => 35, 'tipo' => 2],
            ['id' => 42, 'build_id' => 6, 'equipment_id' => 168, 'tipo' => 3],
            ['id' => 43, 'build_id' => 7, 'equipment_id' => 4, 'tipo' => 1],
            ['id' => 44, 'build_id' => 7, 'equipment_id' => 16, 'tipo' => 2],
            ['id' => 45, 'build_id' => 7, 'equipment_id' => 22, 'tipo' => 2],
            ['id' => 46, 'build_id' => 7, 'equipment_id' => 58, 'tipo' => 2],
            ['id' => 47, 'build_id' => 7, 'equipment_id' => 59, 'tipo' => 2],
            ['id' => 48, 'build_id' => 7, 'equipment_id' => 65, 'tipo' => 2],
            ['id' => 49, 'build_id' => 7, 'equipment_id' => 12, 'tipo' => 3],
            ['id' => 71, 'build_id' => 10, 'equipment_id' => 53, 'tipo' => 1],
            ['id' => 72, 'build_id' => 10, 'equipment_id' => 257, 'tipo' => 2],
            ['id' => 73, 'build_id' => 10, 'equipment_id' => 243, 'tipo' => 2],
            ['id' => 74, 'build_id' => 10, 'equipment_id' => 269, 'tipo' => 2],
            ['id' => 75, 'build_id' => 10, 'equipment_id' => 255, 'tipo' => 2],
            ['id' => 76, 'build_id' => 10, 'equipment_id' => 266, 'tipo' => 2],
            ['id' => 77, 'build_id' => 10, 'equipment_id' => 48, 'tipo' => 3],
            ['id' => 120, 'build_id' => 13, 'equipment_id' => 4, 'tipo' => 1],
            ['id' => 121, 'build_id' => 13, 'equipment_id' => 16, 'tipo' => 2],
            ['id' => 122, 'build_id' => 13, 'equipment_id' => 17, 'tipo' => 2],
            ['id' => 123, 'build_id' => 13, 'equipment_id' => 18, 'tipo' => 2],
            ['id' => 124, 'build_id' => 13, 'equipment_id' => 19, 'tipo' => 2],
            ['id' => 125, 'build_id' => 13, 'equipment_id' => 25, 'tipo' => 2],
            ['id' => 126, 'build_id' => 13, 'equipment_id' => 4, 'tipo' => 3],
            ['id' => 141, 'build_id' => 8, 'equipment_id' => 3, 'tipo' => 1],
            ['id' => 142, 'build_id' => 8, 'equipment_id' => 1, 'tipo' => 2],
            ['id' => 143, 'build_id' => 8, 'equipment_id' => 7, 'tipo' => 2],
            ['id' => 144, 'build_id' => 8, 'equipment_id' => 18, 'tipo' => 2],
            ['id' => 145, 'build_id' => 8, 'equipment_id' => 24, 'tipo' => 2],
            ['id' => 146, 'build_id' => 8, 'equipment_id' => 15, 'tipo' => 2],
            ['id' => 147, 'build_id' => 8, 'equipment_id' => 5, 'tipo' => 3],
            ['id' => 155, 'build_id' => 15, 'equipment_id' => 918, 'tipo' => 1],
            ['id' => 156, 'build_id' => 15, 'equipment_id' => 5, 'tipo' => 1],
            ['id' => 157, 'build_id' => 15, 'equipment_id' => 26, 'tipo' => 2],
            ['id' => 158, 'build_id' => 15, 'equipment_id' => 32, 'tipo' => 2],
            ['id' => 159, 'build_id' => 15, 'equipment_id' => 18, 'tipo' => 2],
            ['id' => 160, 'build_id' => 15, 'equipment_id' => 14, 'tipo' => 2],
            ['id' => 161, 'build_id' => 15, 'equipment_id' => 25, 'tipo' => 2],
            ['id' => 162, 'build_id' => 15, 'equipment_id' => 3, 'tipo' => 3],
            ['id' => 177, 'build_id' => 16, 'equipment_id' => 6, 'tipo' => 1],
            ['id' => 178, 'build_id' => 16, 'equipment_id' => 16, 'tipo' => 2],
            ['id' => 179, 'build_id' => 16, 'equipment_id' => 17, 'tipo' => 2],
            ['id' => 180, 'build_id' => 16, 'equipment_id' => 23, 'tipo' => 2],
            ['id' => 181, 'build_id' => 16, 'equipment_id' => 24, 'tipo' => 2],
            ['id' => 182, 'build_id' => 16, 'equipment_id' => 15, 'tipo' => 2],
            ['id' => 183, 'build_id' => 16, 'equipment_id' => 5, 'tipo' => 3],
            ['id' => 200, 'build_id' => 18, 'equipment_id' => 391, 'tipo' => 1],
            ['id' => 201, 'build_id' => 18, 'equipment_id' => 609, 'tipo' => 1],
            ['id' => 202, 'build_id' => 18, 'equipment_id' => 16, 'tipo' => 2],
            ['id' => 203, 'build_id' => 18, 'equipment_id' => 17, 'tipo' => 2],
            ['id' => 204, 'build_id' => 18, 'equipment_id' => 23, 'tipo' => 2],
            ['id' => 205, 'build_id' => 18, 'equipment_id' => 19, 'tipo' => 2],
            ['id' => 206, 'build_id' => 18, 'equipment_id' => 25, 'tipo' => 2],
            ['id' => 207, 'build_id' => 18, 'equipment_id' => 3, 'tipo' => 3],
            ['id' => 224, 'build_id' => 20, 'equipment_id' => 4, 'tipo' => 1],
            ['id' => 225, 'build_id' => 20, 'equipment_id' => 16, 'tipo' => 2],
            ['id' => 226, 'build_id' => 20, 'equipment_id' => 12, 'tipo' => 2],
            ['id' => 227, 'build_id' => 20, 'equipment_id' => 8, 'tipo' => 2],
            ['id' => 228, 'build_id' => 20, 'equipment_id' => 14, 'tipo' => 2],
            ['id' => 229, 'build_id' => 20, 'equipment_id' => 20, 'tipo' => 2],
            ['id' => 230, 'build_id' => 20, 'equipment_id' => 5, 'tipo' => 3],
            ['id' => 293, 'build_id' => 22, 'equipment_id' => 4, 'tipo' => 1],
            ['id' => 294, 'build_id' => 22, 'equipment_id' => 11, 'tipo' => 2],
            ['id' => 295, 'build_id' => 22, 'equipment_id' => 17, 'tipo' => 2],
            ['id' => 296, 'build_id' => 22, 'equipment_id' => 23, 'tipo' => 2],
            ['id' => 297, 'build_id' => 22, 'equipment_id' => 24, 'tipo' => 2],
            ['id' => 298, 'build_id' => 22, 'equipment_id' => 20, 'tipo' => 2],
            ['id' => 299, 'build_id' => 22, 'equipment_id' => 4, 'tipo' => 3],
            ['id' => 300, 'build_id' => 11, 'equipment_id' => 3, 'tipo' => 1],
            ['id' => 301, 'build_id' => 11, 'equipment_id' => 11, 'tipo' => 2],
            ['id' => 302, 'build_id' => 11, 'equipment_id' => 12, 'tipo' => 2],
            ['id' => 303, 'build_id' => 11, 'equipment_id' => 13, 'tipo' => 2],
            ['id' => 304, 'build_id' => 11, 'equipment_id' => 19, 'tipo' => 2],
            ['id' => 305, 'build_id' => 11, 'equipment_id' => 20, 'tipo' => 2],
            ['id' => 306, 'build_id' => 11, 'equipment_id' => 5, 'tipo' => 3],
            ['id' => 331, 'build_id' => 23, 'equipment_id' => 5, 'tipo' => 1],
            ['id' => 332, 'build_id' => 23, 'equipment_id' => 319, 'tipo' => 1],
            ['id' => 333, 'build_id' => 23, 'equipment_id' => 6, 'tipo' => 2],
            ['id' => 334, 'build_id' => 23, 'equipment_id' => 7, 'tipo' => 2],
            ['id' => 335, 'build_id' => 23, 'equipment_id' => 13, 'tipo' => 2],
            ['id' => 336, 'build_id' => 23, 'equipment_id' => 14, 'tipo' => 2],
            ['id' => 337, 'build_id' => 23, 'equipment_id' => 15, 'tipo' => 2],
            ['id' => 338, 'build_id' => 23, 'equipment_id' => 4, 'tipo' => 3],
        ));
    }
}